name = "opt-maze"
version = "0.1.0"
defaultTargets = ["opt-maze"]

[[lean_lib]]
name = "OptMaze"

[[lean_exe]]
name = "opt-maze"
root = "Main"

[[require]]
name = "lean4-cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.29.0"
